import { createElement } from "@lwc/engine-dom";
import AhaGeoMap from "c/ahaGeoMap";

describe("c-aha-geo-map", () => {
  afterEach(() => {
    while (document.body.firstChild) {
      document.body.removeChild(document.body.firstChild);
    }
  });

  it("TODO: test case generated by CLI command, please fill in test logic", () => {
    // Arrange
    const element = createElement("c-aha-geo-map", {
      is: AhaGeoMap
    });

    // Act
    document.body.appendChild(element);

    // Assert
    // const div = element.shadowRoot.querySelector('div');
    expect(1).toBe(1);
  });
});
